# YOLO-OBB 6-Class Dataset Configuration (merged bottom + upper views)
path: /home/hice1/yloh30/scratch/Lizard_Toepads/data/dataset_obb_6class
train: images/train
val: images/val
test:  # Optional

names:
  0: up_finger
  1: up_toe
  2: bot_finger
  3: bot_toe
  4: ruler
  5: id
